[languages]
Python=""
Rust=""
# Html=""
Java=""
C=""
# Go=""
Lua=""

[tools]
vim=""
Git=""
Linux=""

[[header_info]]
icon = "Phone"
val = "(847) 848-8813"

[[header_info]]
val = "mailto:ben.kunkle@gmail.com"
icon="At"
pretty = "ben.kunkle@gmail.com"
href = true

[[header_info]]
val = "https://github.com/probably-neb"
icon = "Github"
pretty = "probably-neb"
href = true

[[header_info]]
val = "https://nebsite.website"
icon="Globe"
pretty = "nebsite.website"
href = true

[[header_info]]
val = "https://www.linkedin.com/in/benjamin-kunkle/"
icon="Linkedin"
pretty="benjamin-kunkle"
href=true

[[projects]]
name = "Millipyde"
exclude = false
skills = ["Team Work", "Collaboration"]
type = "Research Project"
url = "https://digitalcommons.calpoly.edu/theses/2374/"
short = "A project I recently became involved with working on a tool that adds datatypes for gpu backed arrays and images to Python"

[[projects]]
name = "Ant Simulation"
type = "Personal Project"
url = "https://nebsite.website/modules/ant-sim/index.html"
short = "Simulating date retreival in peer-to-peer (P2P) networks with a system inspired by ants"
skills= [ "Algorithms", "Rust", "Game Dev", "Simulation", "Research" ]
steps = [
    "Conducted research on P2P networks inspired by ant pheromone systems and developed a visual simulation of the algorithm.",
    # "Developed a toolkit for benchmarking the program after each improvement to measure and verify progress",
    "Created a comprehensive report documenting the research and design process, including a live demonstration of the program using WebAssembly."
]

[[projects]]
name="Wave Function Collapse"
url = "https://nebsite.website/modules/wfc-rust/index.html"
type="Personal Project"
short="Implementation of Wave Function Collapse, the constraint based bitmap generation algorithm created by Maxim Gumin."
skills = ["Algorithms", "Adaptability", "Haskell", "Rust"]
steps = [
    "Implemented algorithm in Haskell, but quickly hit dead ends.",
    "Rewrote it in Rust to gain new perspective.",
    "Used winit and wgpu created a desktop and a web based viewer for the Rust implementation."
]

[[projects]]
skills = ["Leadership", "Responsibility", "Accountability"]
name = "Camp Towering Pines For Boys" 
type = "Camp Counselor"
dates = "Summers of 2021 and 2022"
short = "Six week overnight camp in Northern Wisconsin. I was personably responsible for a cabin of 15 boys aged 14-16 each summer."

[[projects]]
name = "Smaller Projects"
# type = "Personal Projects"
skills = ["Solving Problems", "Exploring/Experimenting"]
short = "I love working and playing with computers and look for excuses to do both"
steps = [
    "Created Goclone, a cli tool that uses rclone for backing up files to Dropbox to save battery.",
    "Developed a resume generation system using TOML, LaTeX, and Jinja2 to separate formatting and content, allowing for quick iteration and easy updates.",
    "Enjoyed college course on Systems Programming, where projects were built from scratch in C, including a word frequency counter using a trie, Huffman encoding/decoding and simplified versions of GNU Tar, Talk, and Uniq."
]
# desc_long=true
# steps = [
#     "[Goclone] A cli tool I made that uses rclone to handle backing up files to Dropbox as the Dropbox client was draining too much of my battery",
#     "[Resume] This resume was generated by inserting the contents of a toml file into a \\LaTeX{} template using jinja2. I created this system to separate formatting and content. It allows me to iterate quickly and simplifies the process of updating and creating new versions.",
#     "[Systems Programming] My favorite college course I've taken. Each project in the course was created from scratch in C, including a word frequency counter that could process 1 million words in 7ms using a trie, Huffman encoding/decoding, and simplified versions of GNU Tar, Talk, and Uniq"
#     # "[Linux] My computer runs on a Linux operating system. I see it as a platform for me to explore, tinker, and try new things.",
# ]



[calpoly]
notable_completed = [
    "Data Structures",
    "Computer Architecture",
    "Systems Programming",
    "Discrete Structures"
]
completed = [
    "Data Structures",
    "Proj-Based Obj-Oriented Programming & Design",
    "Computer Architecture",
    "Systems Programming",
    "Introduction to Computer Organization",
    "Discrete Structures",
]
current = [
    "Design & Analysis of Algorithms"
]
